name: Boot Smoke Tests | Actuator Webmvc
on:
  push:
    branches:
      - 'github-actions'
jobs:
  actuator_webmvc_app_test:
    name: Actuator Webmvc App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: boot:actuator-webmvc
      task: appTest
  actuator_webmvc_native_app_test:
    name: Actuator Webmvc Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: boot:actuator-webmvc
      task: nativeAppTest
