name: Boot Smoke Tests | Mustache Webmvc
on:
  push:
    branches:
      - 'github-actions'
jobs:
  mustache_webmvc_app_test:
    name: Mustache Webmvc App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: boot:mustache-webmvc
      task: appTest
  mustache_webmvc_native_app_test:
    name: Mustache Webmvc Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: boot:mustache-webmvc
      task: nativeAppTest
