name: Boot Smoke Tests | Logging Logback Xml
on:
  push:
    branches:
      - 'github-actions'
jobs:
  logging_logback_xml_app_test:
    name: Logging Logback Xml App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: boot:logging-logback-xml
      task: appTest
  logging_logback_xml_native_app_test:
    name: Logging Logback Xml Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: boot:logging-logback-xml
      task: nativeAppTest
