name: Cloud Smoke Tests | Cloud Stream Pulsar
on:
  push:
    branches:
      - 'github-actions'
jobs:
  cloud_stream_pulsar_app_test:
    name: Cloud Stream Pulsar App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: cloud:cloud-stream-pulsar
      task: appTest
  cloud_stream_pulsar_native_app_test:
    name: Cloud Stream Pulsar Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: cloud:cloud-stream-pulsar
      task: nativeAppTest
