name: Cloud Smoke Tests | Cloud Stream Rabbit
on:
  push:
    branches:
      - 'github-actions'
jobs:
  cloud_stream_rabbit_app_test:
    name: Cloud Stream Rabbit App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: cloud:cloud-stream-rabbit
      task: appTest
  cloud_stream_rabbit_native_app_test:
    name: Cloud Stream Rabbit Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: cloud:cloud-stream-rabbit
      task: nativeAppTest
