name: Cloud Smoke Tests | Cloud Loadbalancing Web
on:
  push:
    branches:
      - 'github-actions'
jobs:
  cloud_loadbalancing_web_app_test:
    name: Cloud Loadbalancing Web App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: cloud:cloud-loadbalancing-web
      task: appTest
  cloud_loadbalancing_web_native_app_test:
    name: Cloud Loadbalancing Web Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: cloud:cloud-loadbalancing-web
      task: nativeAppTest
