name: Data Smoke Tests | Data Redis
on:
  push:
    branches:
      - 'github-actions'
jobs:
  data_redis_app_test:
    name: Data Redis App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: data:data-redis
      task: appTest
  data_redis_native_app_test:
    name: Data Redis Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: data:data-redis
      task: nativeAppTest
