name: Data Smoke Tests | Hateoas
on:
  push:
    branches:
      - 'github-actions'
jobs:
  hateoas_app_test:
    name: Hateoas App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: data:hateoas
      task: appTest
  hateoas_native_app_test:
    name: Hateoas Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: data:hateoas
      task: nativeAppTest
