name: Data Smoke Tests | Data Redis Reactive
on:
  push:
    branches:
      - 'github-actions'
jobs:
  data_redis_reactive_app_test:
    name: Data Redis Reactive App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: data:data-redis-reactive
      task: appTest
  data_redis_reactive_native_app_test:
    name: Data Redis Reactive Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: data:data-redis-reactive
      task: nativeAppTest
