name: Data Smoke Tests | Data Rest Mongodb
on:
  push:
    branches:
      - 'github-actions'
jobs:
  data_rest_mongodb_app_test:
    name: Data Rest Mongodb App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: data:data-rest-mongodb
      task: appTest
  data_rest_mongodb_native_app_test:
    name: Data Rest Mongodb Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: data:data-rest-mongodb
      task: nativeAppTest
