name: Framework Smoke Tests | Webflux Netty
on:
  push:
    branches:
      - 'github-actions'
jobs:
  webflux_netty_app_test:
    name: Webflux Netty App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:webflux-netty
      task: appTest
  webflux_netty_native_app_test:
    name: Webflux Netty Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:webflux-netty
      task: nativeAppTest
  webflux_netty_test:
    name: Webflux Netty Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:webflux-netty
      task: test
  webflux_netty_native_test:
    name: Webflux Netty Native Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:webflux-netty
      task: nativeTest
