name: Framework Smoke Tests | Cache Redis
on:
  push:
    branches:
      - 'github-actions'
jobs:
  cache_redis_app_test:
    name: Cache Redis App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:cache-redis
      task: appTest
  cache_redis_native_app_test:
    name: Cache Redis Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:cache-redis
      task: nativeAppTest
