name: Framework Smoke Tests | Scheduled
on:
  push:
    branches:
      - 'github-actions'
jobs:
  scheduled_app_test:
    name: Scheduled App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:scheduled
      task: appTest
  scheduled_native_app_test:
    name: Scheduled Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:scheduled
      task: nativeAppTest
