name: Framework Smoke Tests | Cache Simple Jdk Proxy
on:
  push:
    branches:
      - 'github-actions'
jobs:
  cache_simple_jdk_proxy_app_test:
    name: Cache Simple Jdk Proxy App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:cache-simple-jdk-proxy
      task: appTest
  cache_simple_jdk_proxy_native_app_test:
    name: Cache Simple Jdk Proxy Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:cache-simple-jdk-proxy
      task: nativeAppTest
