name: Framework Smoke Tests | Webflux Jetty
on:
  push:
    branches:
      - 'github-actions'
jobs:
  webflux_jetty_app_test:
    name: Webflux Jetty App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:webflux-jetty
      task: appTest
  webflux_jetty_native_app_test:
    name: Webflux Jetty Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:webflux-jetty
      task: nativeAppTest
  webflux_jetty_test:
    name: Webflux Jetty Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:webflux-jetty
      task: test
  webflux_jetty_native_test:
    name: Webflux Jetty Native Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:webflux-jetty
      task: nativeTest
