name: Integration Smoke Tests | Spring Kafka Streams
on:
  push:
    branches:
      - 'github-actions'
jobs:
  spring_kafka_streams_app_test:
    name: Spring Kafka Streams App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: integration:spring-kafka-streams
      task: appTest
  spring_kafka_streams_native_app_test:
    name: Spring Kafka Streams Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: integration:spring-kafka-streams
      task: nativeAppTest
