name: Security Smoke Tests | Security Oauth2 Authorization Server
on:
  push:
    branches:
      - 'github-actions'
jobs:
  security_oauth2_authorization_server_app_test:
    name: Security Oauth2 Authorization Server App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: security:security-oauth2-authorization-server
      task: appTest
  security_oauth2_authorization_server_native_app_test:
    name: Security Oauth2 Authorization Server Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: security:security-oauth2-authorization-server
      task: nativeAppTest
